# Python Notes: Numpy II
<hr>

Arrays can have multiple dimensions  
> Simply cast a list with nested lists of equal elements per list into an array  
>> Each nested list corresponds to a dimension in the array  
  
Dimensions relates to the depth of nested lists in the array, rather than the number of nested lists  
> the number of nested lists determines the shape of the array  
  
REFRESHER: 
**_myArray_.ndim**  
> returns the depth of the nesting  
**_myArray_.shape**  
> returns the number of rows (numbner of lists nested) [each list represents a row] then columns of the array (size of each nested list); (# of rows, # of columns)  
**_myArray_.size**  
> number of elements in the array = product of the shape  
  
* Slicing in arrays are end point exclusive (the ending index selected is not included in the slice)  

<hr>  

#### Operations

**REMINDER:**  
Don't forget to convert the lists into arrays when array operations is the goal

Operations work similar as to when there is only one dimension where the operation is done to each array with the corresponding coordinates  
> This applies to everything except Matrix Multiplication; Scalar and Hadamard Multiplications functions intuitively and similarly to 1D arrays  
>> The shape and dimension of the matrices have to be the same for Hadamard Multiplication to work  
  
  
Matrix Multiplication is different  
> The number of columns in the first array has to equal the number of rows of the second array; the shape of the matrix multiplication is based on the row of the first array and columns of the second array; <br> (_PS: Matrices are read as [rows, columns]_)  
>> M is an [x,y] matrix and N is a [y,z]; the resulting shape from a matrix multiplication is a [x,z] matrix  
>>> MN multiplication matrix and NM multiplication matrix is not the same  
>> Dot product of each combination is the resulting value for the coordinate    
>>> <br>_Example:_ <br> array A has a shape of [2,3] and array B has a shape of [3,2]  
>>> Dot product of array A row 1 by array B column 1 is done first;  
>>> Then the dot product of array A row 1 by array B column 2  
>>>> These 2 dot products will yield the product of positions [0,0] and [0,1] based on [a,b] (rows of a and columns of y); the product position is based on the dimensions used (in this case Row 1 and Column 1 and Row 1 and Column 2)  
[x, y  
?, ?]  
>>>> Alternatively, this can be thought in reverse order; I want to know the matrix product for position, [1,0]; that means get the dot product of Row 2 (of a) Column 1 (of b), similar to just reading an array  
  
To do Matrix Multiplcation in Python Numpy, use Dot Product of 2 arrays



In [ ]:
import numpy as np

# dot product of 2 arrays/ matrix multiplication
# M is a [3,2] matrix; N is a [2,5]; MN is a 
M = np.array([[2,3],[5,1],[9,3]])
N = np.array([[3,2,1,5643,123],[1,5,8,32,54]])

MN = np.dot(M,N)

print("Dot Product of M and N is: \n", MN)

# hamard multiplication
a = np.array([[2,4],[3,6]])
b = np.array([[4,8],[1,9]])

c = a*b
print("Hadamard Multiplication of a and b is: \n", c)  

# scalar multiplication
d = a*2

print("Scalar Multiplication fo a by 2 is: \n", d)

Dot Product of M and N is: 
 [[    9    19    26 11382   408]
 [   16    15    13 28247   669]
 [   30    33    33 50883  1269]]
Hadamard Multiplication of a and b is: 
 [[ 8 32]
 [ 3 54]]
Scalar Multiplication fo a by 2 is: 
 [[ 4  8]
 [ 6 12]]


In [16]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12],[13,14,15]])

result = np.dot(arr1,arr2)
print(result)

[[ 66  72  78]
 [156 171 186]]
