# Python Notes: Numpy I
<hr>

Numpy is for scientific computing and the basis for the Pandas module    
Numpy Arrays are similar to lists but fixed in sized and all contain one type of element

**import numpy as np**  
Import numpy and rename  
  
**_myArray_ = np.array(_myList_)**  
casts a list into an array  
  
**_myArray_.dtype**  
returns the data type of the element within the ndarray  
> the data type of the numpy array is called an nd array  
  
  **_myArray_.size**  
  returns the number of elements in the array  
    
**_myArray_.ndim**  
returns the number of dimensions or rank of the array  
  
**_myArray_.shape**  
returns a tuple which specify the size of the array in each dimension  

In [1]:
import numpy as np

myList = [1,2,3,4,5]
a = np.array(myList)

print("D Type is ",  a.dtype  )
print("Size is ",  a.size  )
print("# of Dimensions are ",  a.ndim  )
print("Shape of array is ",  a.shape  )

D Type is  int32
Size is  5
# of Dimensions are  1
Shape of array is  (5,)


**_myArray_[n] = _new value_**  
accesses the array and replaces it with the new value  
> Has to be same the type as the rest  
  
**_myArray_[x:y:z] = _new value1_, ..., _newvalueN_**  
Arrays can be sliced similar to lists; can now reassign a group of elements using slice    
> the ending point for the index is non inclusive; the value is the first index to not include in the split  
  
**_myArray[myIndexList]_ = _value elements with indices in myIndexList_**  
List of integers can be used to replace multiple indices with one value or with multiple values  


In [5]:
myList = [1,2,3,4,5]
a = np.array(myList)
print(a)

a[1:4] = -3,-2,-1
print(a)

myIndices = [0,2,4]
a[myIndices] = -100
print(a)

myValues = [300,100,0]
a[myIndices] = myValues
print(a)

[1 2 3 4 5]
[ 1 -3 -2 -1  5]
[-100   -3 -100   -1 -100]
[300  -3 100  -1   0]


### Basic Operations

##### Vector Operations

These operations are much faster and memory efficient with numpy than vanilla python, which would require loops  
  
**_a_ = _b_ +/- _c_**  
array _b_ and _c_ has to be both arrays  
> the operation is done on each element of the corresponing indices of both arrays  
>> another way to write the code is: **_a_ = np.add(_a_,_b_)** or **_a_ = np.divide(_a_,_b_)** or **_a_ = np.subtract(_a_,_b_)**  

In [7]:
a = np.array([1,2,3])
b = np.array([1,2,3])

c = a+b
d = a-b
e = a/b

print(c)
print(d)
print(e)

[2 4 6]
[0 0 0]
[1. 1. 1.]


**_a_ = _n_ + _b_**  
adds the constant to all elements in array _b_  
> n is a constant  
>> otherwise known as broadcasting  



In [7]:
c = 1 + b
c

array([2, 3, 4])

##### Multiplication  

**_a_ = _n_ _b_**  
Scalar multiplication involves multiplying all elements by the one mutiplier  
> n being a constant  
  
**_a_ = _b_ \* _c_**
Hadamard product involves multiplying each 
> works similar to vector operations but with multiplication  
  
**_a_ = np.dot(_b_,_c_)**  
Dot product represents how similar two vectors are  
> it is similar to Hadamard product but adds the products of the resulting elements in the array  
>> arrays with a dot product of zero indicate that the vectors are perpendicular to each other  


In [9]:
a = np.array([1,2,3])
b = np.array([1,2,3])

x = 2*b
print(x)

y = a*b
print(y)

z = np.dot(a,b)
print(z)

[2 4 6]
[1 4 9]
14


<hr>

### Universal Functions


Universal functions are functions that work on nd arrays
  
**_result_ = _myArray_.mean()**  
returns the mean of the elements  
  
**_result_ = _myArray_.max()**  
returns the highest number in the array  
  
**_result_ = _myArray_.min()**  
returns the lowest number in the array  
  
**_result_ = _myArray_.std()**  
returns the standard deviation of the elements  
  
**np.linspace(_starting point_, _ending point_, num=_number of samples to generate_)**  
returns an array of evenly spaced numbers from the starting point to the end point over num times  
> the ending point is inclusive  



In [6]:
a = np.array([1,2,3])
b = np.array([1,2,3])

print("The mean is ",   a.mean()  )
print("The max is ",   a.max()  )
print("The min is ",   a.min()  )
print("The min is ",   a.std()  )
print("The numbers to plot a x axis starting from 0 to 10 with 5 numbers to do so is", np.linspace(0,10,num=5))

The mean is  2.0
The max is  3
The min is  1
The min is  0.816496580927726
The numbers to plot a x axis starting from 0 to 10 with 5 numbers to do so is [ 0.   2.5  5.   7.5 10. ]
